name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  changelog:
    required: true
    description: 'path to the changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
