name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update Changelog
        id: update-changelog
        uses: ./.github/actions/prepare-release
        with:
          changelog: ${{ github.workspace }}/CHANGELOG.md
      - name: Output Version
        run: echo ${{ steps.update-changelog.outputs.new-version }}
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ steps.update-changelog.outputs.new-version }}
          title: Prepare for ${{ steps.update-changelog.outputs.new-version }}
          draft: true
