name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update Changelog
        id: update-changelog
        uses: ./.github/actions/prepare-release
        with:
          changelog: ${{ github.workspace }}/CHANGELOG.md
      - name: Output Version
        run: echo ${{ steps.update-changelog.outputs.new-version }}
      - name: Update package.json
        id: update-package-json
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '"version": "[^"]*"'
          replace: '"version": "${{ steps.update-changelog.outputs.new-version }}"'
          include: package.json
      - name: Output 1
        run: echo ${{ steps.update-package-json.outputs.modifiedFiles }}
      - name: Update AssemblyInfo.props
        id: update-assembly-info
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '<VersionPrefix>[^<]*<\/VersionPrefix>'
          replace: '<VersionPrefix>${{ steps.update-changelog.outputs.new-version }}</VersionPrefix>'
          include: AssemblyInfo.props
      - name: Output 1
        run: echo ${{ steps.update-assembly-info.outputs.modifiedFiles }}
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ steps.update-changelog.outputs.new-version }}
          title: Prepare for ${{ steps.update-changelog.outputs.new-version }}
          draft: true
          body: An automated PR for next release.
