name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update Changelog
        id: update-changelog
        uses: ./.github/actions/prepare-release
      - name: Output Version
        run: echo ${{ steps.update-changelog.outputs.new-version }}
